version: '2.3'

services:
    ultralytics:
        image: ultralytics-ours
        container_name: ultralytics-ours
        build: .
        privileged: true
        runtime: nvidia
        shm_size: 64gb
        tty: true
        stdin_open: true
        network_mode: host
        working_dir: /ws
        volumes:
           - $PWD/yolo:/ws
           - /dev:/dev
