version: '3.3'

services:
    ultralytics:
        image: ultralytics/ultralytics:latest-jetson # this image has no GPU!
        container_name: ultralytics
        shm_size: 64gb
        tty: true
        stdin_open: true
        network_mode: host
        working_dir: /ws
        volumes:
           - $PWD/yolo:/ws
        devices:
            - /dev/nvidia0