version: '3'

vars:
    UNUSED: Hello, World! 

tasks:
    yolo_get_pretrained:
        cmds: 
            - echo 'Wait for weights to download and ^C! [press Enter to continue]' && read 
            - docker compose run ultralytics 'yolo detect'

    yolo_train:
        cmds: 
            - docker compose run ultralytics 'yolo train data=dataset.yaml amp=False'

    yolo_export_nvds:
        cmds:
            - docker compose run ultralytics "yolo export model=runs/detect/train2/weights/best.pt format=engine device=0"
            - echo 'Fetch your model at runs/detect/train2/weights/best.pt.'

    nvds_install:
        cmds:
            - apt install deepstream-6.2
            - cd nvds/DeepStream-Yolo && CUDA_VER=11.4 make -C nvdsinfer_custom_impl_Yolo

    nvds_run:
        cmds:
            - echo NOT IMPLEMENTED
        
